// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDE5r7ID46NOxlxylDqPVzxZwjFofodHk',
    appId: '1:525398410401:web:5d12f531a3da04d1075ce0',
    messagingSenderId: '525398410401',
    projectId: 'karaz-app',
    authDomain: 'karaz-app.firebaseapp.com',
    storageBucket: 'karaz-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSdi3wmjQPt95ABHhUtTFu2ybw8qR6eVA',
    appId: '1:525398410401:android:b9869abe5eea118b075ce0',
    messagingSenderId: '525398410401',
    projectId: 'karaz-app',
    storageBucket: 'karaz-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVolGk5tNNXnWPAKxqIRrw4Bl-EMD400k',
    appId: '1:525398410401:ios:89921248baec6baf075ce0',
    messagingSenderId: '525398410401',
    projectId: 'karaz-app',
    storageBucket: 'karaz-app.appspot.com',
    iosClientId: '525398410401-g3u9l4te3odkt2kjlifvbg6vjcjqv2bl.apps.googleusercontent.com',
    iosBundleId: 'com.example.karazShoppingOrganization',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVolGk5tNNXnWPAKxqIRrw4Bl-EMD400k',
    appId: '1:525398410401:ios:89921248baec6baf075ce0',
    messagingSenderId: '525398410401',
    projectId: 'karaz-app',
    storageBucket: 'karaz-app.appspot.com',
    iosClientId: '525398410401-g3u9l4te3odkt2kjlifvbg6vjcjqv2bl.apps.googleusercontent.com',
    iosBundleId: 'com.example.karazShoppingOrganization',
  );
}
